package com.lkuprashvili.chat.utils

object Const {
    const val NICKNAME = "nickname"
    const val DB_ERROR = "DB Error"
    const val AUTH_FAILED = "Auth Failed"
    const val NICKNAME_CHECK_FAILED = "Nickname check failed"
    const val LOGIN_FAILED = "Login failed"
    const val FILL_ALL_FIELDS = "Fill all fields"
    const val REGISTRATION_FAILED = "Registration failed"
    const val CHATS = "chats"
    const val USERS = "users"
    const val NOT_LOGGED_IN = "Not Logged in"
    const val TIMESTAMP = "timestamp"
    const val PHOTO_URL = "photoUrl"
    const val LAST_MESSAGE = "lastMessage"
    const val PROFESSION = "profession"
    const val ZERO = "0"
    const val ONE = "1"
    const val USER_PROFILE = "user_profile"
    const val IMAGE_URI = "profile_image_uri"
    const val CHAT_ID = "chatId"
    const val USER_ID = "userId"
    const val OTHER_USER_ID = "otherUserId"
    const val USER_NAME = "userName"
    const val USER_ROLE = "userRole"
    const val INVALID_CHAT_ID = "Invalid chat ID"
    const val MESSAGES = "messages"
    const val FAILED_TO_SEND = "Failed to send message"
    const val FAILED_TO_LOAD = "Failed to load message"
    const val NO_CHATS = "No chats available"
    const val LOADING = "Loading..."
    const val PROFILE_UPLOADED = "Profile updated"
    const val UPDATE_FAILED = "Update failed"
    const val FAILED_TO_LOAD_PROFILE = "Failed to load profile"
    const val PHOTO_UPLOADED_SUCCESSFULLY = "Photo uploaded successfully"
    const val CONVERSATIONS = "conversations"

}